// This file is auto-generated by @hey-api/openapi-ts

import { oc } from '@orpc/contract';
import { openapi } from '@orpc/openapi';
import * as z from 'zod';

import { zGetItemsQuery, zGetItemsResponse } from './zod.gen';

/**
 * Get all items
 */
export const getItems = oc.meta(openapi({
  inputStructure: 'detailed',
  method: 'GET',
  operationId: 'getItems',
  path: '/items',
  summary: 'Get all items',
  tags: ['items']
})).input(z.object({ query: zGetItemsQuery.optional() }).optional()).output(zGetItemsResponse);

export const contract = {
  getItems
};
