// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod/v4-mini';

export const zBar = z.strictObject({
  bar: z.nullable(z.array(z.lazy((): any => zBar)))
});

export const zFoo = z.strictObject({
  foo: zBar
});
