// This file is auto-generated by @hey-api/openapi-ts

import { oc } from '@orpc/contract';
import { openapi } from '@orpc/openapi';

export const foo = oc.meta(openapi({
  inputStructure: 'detailed',
  method: 'GET',
  operationId: 'foo',
  path: '/foo',
  tags: ['default']
}));

export const bar = oc.meta(openapi({
  inputStructure: 'detailed',
  method: 'GET',
  operationId: 'bar',
  path: '/bar',
  tags: ['default']
}));

export const contract = {
  foo,
  bar
};
