// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zBar = z.strictObject({
  bar: z.array(z.lazy((): any => zBar)).nullable()
});

export const zFoo = z.strictObject({
  foo: zBar
});
