// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod/v3';

export const zBar: z.AnyZodObject = z.strictObject({
  bar: z.array(z.lazy(() => zBar)).nullable()
});

export const zFoo = z.strictObject({
  foo: zBar
});
