// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zIds = z.array(z.string());

export const zItem = z.object({
  id: z.string(),
  name: z.string()
});

export const zGetItemsQuery = z.object({
  ids: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  names: z.array(z.string()).optional(),
  codes: z.array(z.string()).optional(),
  category: z.string().optional(),
  keyword: z.string().optional(),
  refIds: zIds.optional(),
  filters: z.record(z.string(), z.string()).optional(),
  pipeFilters: z.record(z.string(), z.string()).optional(),
  spaceFilters: z.record(z.string(), z.string()).optional(),
  facets: z.record(z.string(), z.string()).optional()
});

/**
 * List of items
 */
export const zGetItemsResponse = z.array(zItem);
